### ISSUE TITLE
Effects created on items don't show the Source

### ISSUE THREAD

**Issue by yjeroen** [asacolips-projects/boilerplate#28]
Bug:
![image](https://github.com/asacolips-projects/boilerplate/assets/1303988/ddd29010-2f05-495a-b982-919068e290ad)

Solution:
templates/item/effects.hbs is missing `data-origin="{{@root.item.uuid}}"` after line 22.

Note: Only verified on ChaosOS's V12 branch https://github.com/JPMeehan/boilerplate/tree/v12

**Comment by yjeroen** [comment]
Also, I believe in the actor/effects.hbs and item/effects.hbs template it should use the parents name instead of the source name.

```html
<div class='effect-source'>{{effect.parent.name}}</div>
```

**Comment by JPMeehan** [comment]
Fix is simple: in `templates/item/effects.hbs`, on the effect creation add `data-origin="{{@root.item.uuid}}"`

**Comment by JPMeehan** [comment]
@asacolips this is fixed in the v12 branch already and can be closed
