### ISSUE TITLE
templates use DOCUMENTS.Edit, which is not a valid core localization string

### ISSUE THREAD

**Issue by yjeroen** [asacolips-projects/boilerplate#33]
![image](https://github.com/asacolips-projects/boilerplate/assets/1303988/46b5c113-1a7b-4ef0-8da7-882e92f07d5a)

See `game.i18n.translations.DOCUMENT`

Advice: change templates to use Update string.

E.g. features.hbs and spells.hbs
```hbs
              <a
                class='item-control item-edit'
                title='{{localize "DOCUMENT.Update" type='feature'}}'
                data-action='viewDoc'
              >
```

**Comment by JPMeehan** [comment]
Looks like this is already fixed on the gear sheet but a mistake on Spell and Features
